version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    command: ["/app/startup.sh"]
    container_name: service1-container
    ports:
      - "8081:8080" # Adjust ports as necessary
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - mynetwork

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: service2-container
    ports:
      - "8082:8080" # Adjust ports as necessary
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
