version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: |
        FROM maven:3.8.5-openjdk-17
        WORKDIR /app
        COPY pom.xml .
        COPY src ./src
        RUN mvn clean install
        COPY ./target/*.jar ./app.jar
        EXPOSE 8080
        CMD ["java", "-jar", "app.jar"]
    container_name: service1-container
    ports:
      - "8081:8080" # Adjust ports as necessary
    networks:
      - mynetwork

  service2:
    build:
      context: ./service2
      dockerfile: |
        FROM maven:3.8.5-openjdk-17
        WORKDIR /app
        COPY pom.xml .
        COPY src ./src
        RUN mvn clean install
        COPY ./target/*.jar ./app.jar
        EXPOSE 8080
        CMD ["java", "-jar", "app.jar"]
    container_name: service2-container
    ports:
      - "8082:8080" # Adjust ports as necessary
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
